name: build-page
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: Setup yarn
        run: npm install -g yarn

      - run: yarn
      - run: git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/portableCoder/portableThoughts.git
      - run: touch out/.nojekyll
      - run: yarn deploy-ci
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
