name: build-page
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - run: corepack enable
      - run: yarn
      - run: git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/portableCoder/portableThoughts.git
      - run: mkdir -p out
      - run: touch out/.nojekyll
      - run: yarn build
      - run: yarn export
      - run: npx gh-pages -d out -t true -u "github-actions-bot <support+actions@github.com>"
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
